// Generated by npm run sync:recipes. Edit the domain sources, not this file.
export const RECIPE_KNOWLEDGE = {
  "generatedFrom": [
    "three-body/src/game/eland/domain/material.ts",
    "three-body/src/game/eland/domain/interaction-rules.ts",
    "three-body/src/game/eland/domain/separation-rules.ts"
  ],
  "materials": [
    {
      "id": 0,
      "key": "air",
      "name": "空气",
      "phase": "gas",
      "tags": [
        "air"
      ],
      "hardness": 0,
      "mass": 0,
      "color": [
        13,
        20,
        24
      ]
    },
    {
      "id": 1,
      "key": "stone",
      "name": "石",
      "phase": "solid",
      "tags": [
        "solid",
        "ground",
        "building",
        "tool-material"
      ],
      "hardness": 8,
      "mass": 2.4,
      "color": [
        111,
        108,
        102
      ]
    },
    {
      "id": 2,
      "key": "soil",
      "name": "土",
      "phase": "solid",
      "tags": [
        "solid",
        "ground"
      ],
      "hardness": 2,
      "mass": 1.5,
      "color": [
        105,
        78,
        53
      ]
    },
    {
      "id": 3,
      "key": "wet_soil",
      "name": "湿土",
      "phase": "solid",
      "tags": [
        "solid",
        "ground",
        "fertile"
      ],
      "hardness": 2,
      "mass": 1.7,
      "color": [
        96,
        82,
        63
      ]
    },
    {
      "id": 4,
      "key": "rich_soil",
      "name": "沃土",
      "phase": "solid",
      "tags": [
        "solid",
        "ground",
        "fertile"
      ],
      "hardness": 2,
      "mass": 1.5,
      "color": [
        90,
        77,
        55
      ]
    },
    {
      "id": 5,
      "key": "exhausted_soil",
      "name": "贫瘠土",
      "phase": "solid",
      "tags": [
        "solid",
        "ground",
        "exhausted"
      ],
      "hardness": 2,
      "mass": 1.4,
      "color": [
        122,
        91,
        59
      ]
    },
    {
      "id": 6,
      "key": "sand",
      "name": "沙",
      "phase": "solid",
      "tags": [
        "solid",
        "ground"
      ],
      "hardness": 1,
      "mass": 1.4,
      "color": [
        164,
        142,
        91
      ]
    },
    {
      "id": 7,
      "key": "water",
      "name": "水",
      "phase": "liquid",
      "tags": [
        "liquid",
        "drinkable"
      ],
      "hardness": 0,
      "mass": 1,
      "color": [
        28,
        91,
        126
      ],
      "consume": {
        "hydration": 58
      }
    },
    {
      "id": 8,
      "key": "grass",
      "name": "草",
      "phase": "solid",
      "tags": [
        "plant"
      ],
      "hardness": 1,
      "mass": 0.2,
      "color": [
        76,
        106,
        58
      ]
    },
    {
      "id": 9,
      "key": "shrub",
      "name": "灌木",
      "phase": "solid",
      "tags": [
        "plant",
        "flammable"
      ],
      "hardness": 1,
      "mass": 0.5,
      "color": [
        52,
        91,
        45
      ]
    },
    {
      "id": 10,
      "key": "berry_bush",
      "name": "结果灌木",
      "phase": "solid",
      "tags": [
        "plant",
        "flammable"
      ],
      "hardness": 1,
      "mass": 0.6,
      "color": [
        55,
        103,
        51
      ]
    },
    {
      "id": 11,
      "key": "crop_sprout",
      "name": "作物幼苗",
      "phase": "solid",
      "tags": [
        "plant"
      ],
      "hardness": 1,
      "mass": 0.2,
      "color": [
        119,
        137,
        62
      ]
    },
    {
      "id": 12,
      "key": "crop_mature",
      "name": "成熟作物",
      "phase": "solid",
      "tags": [
        "plant"
      ],
      "hardness": 1,
      "mass": 0.7,
      "color": [
        183,
        157,
        63
      ]
    },
    {
      "id": 13,
      "key": "wood",
      "name": "木材",
      "phase": "solid",
      "tags": [
        "solid",
        "fuel",
        "building",
        "tool-material",
        "flammable"
      ],
      "hardness": 4,
      "mass": 1,
      "color": [
        91,
        61,
        38
      ]
    },
    {
      "id": 14,
      "key": "leaves",
      "name": "树叶",
      "phase": "solid",
      "tags": [
        "plant",
        "flammable"
      ],
      "hardness": 1,
      "mass": 0.2,
      "color": [
        44,
        78,
        42
      ]
    },
    {
      "id": 15,
      "key": "packed_soil",
      "name": "夯土",
      "phase": "solid",
      "tags": [
        "solid",
        "ground"
      ],
      "hardness": 3,
      "mass": 1.7,
      "color": [
        123,
        101,
        71
      ]
    },
    {
      "id": 16,
      "key": "fire",
      "name": "火",
      "phase": "gas",
      "tags": [
        "hot"
      ],
      "hardness": 0,
      "mass": 0,
      "color": [
        224,
        94,
        42
      ]
    },
    {
      "id": 17,
      "key": "ash",
      "name": "灰",
      "phase": "solid",
      "tags": [
        "ground"
      ],
      "hardness": 1,
      "mass": 0.2,
      "color": [
        93,
        91,
        87
      ]
    },
    {
      "id": 18,
      "key": "ice",
      "name": "冰",
      "phase": "solid",
      "tags": [
        "solid",
        "ground",
        "drinkable"
      ],
      "hardness": 3,
      "mass": 0.9,
      "color": [
        153,
        202,
        221
      ],
      "consume": {
        "hydration": 34
      }
    },
    {
      "id": 19,
      "key": "plank",
      "name": "木板",
      "phase": "solid",
      "tags": [
        "solid",
        "building",
        "fuel",
        "flammable"
      ],
      "hardness": 4,
      "mass": 0.7,
      "color": [
        155,
        111,
        65
      ]
    },
    {
      "id": 20,
      "key": "fiber",
      "name": "纤维",
      "phase": "solid",
      "tags": [
        "fiber",
        "flammable"
      ],
      "hardness": 1,
      "mass": 0.1,
      "color": [
        173,
        158,
        116
      ]
    },
    {
      "id": 21,
      "key": "food",
      "name": "食物",
      "phase": "solid",
      "tags": [
        "edible"
      ],
      "hardness": 1,
      "mass": 0.2,
      "color": [
        190,
        76,
        80
      ],
      "consume": {
        "nutrition": 48,
        "hydration": 4
      }
    },
    {
      "id": 22,
      "key": "seed",
      "name": "种子",
      "phase": "solid",
      "tags": [
        "seed"
      ],
      "hardness": 1,
      "mass": 0.03,
      "color": [
        163,
        132,
        68
      ]
    },
    {
      "id": 23,
      "key": "rope",
      "name": "绳",
      "phase": "solid",
      "tags": [
        "fiber",
        "building",
        "flammable"
      ],
      "hardness": 2,
      "mass": 0.25,
      "color": [
        167,
        139,
        91
      ]
    },
    {
      "id": 24,
      "key": "stone_tool",
      "name": "石制工具",
      "phase": "solid",
      "tags": [
        "solid",
        "tool"
      ],
      "hardness": 7,
      "mass": 1.1,
      "color": [
        122,
        119,
        109
      ]
    },
    {
      "id": 25,
      "key": "cooked_food",
      "name": "熟食",
      "phase": "solid",
      "tags": [
        "edible"
      ],
      "hardness": 1,
      "mass": 0.2,
      "color": [
        174,
        91,
        49
      ],
      "consume": {
        "nutrition": 60,
        "hydration": 3,
        "health": 2
      }
    },
    {
      "id": 26,
      "key": "clothing",
      "name": "衣物",
      "phase": "solid",
      "tags": [
        "insulating"
      ],
      "hardness": 1,
      "mass": 0.6,
      "color": [
        123,
        91,
        73
      ]
    },
    {
      "id": 27,
      "key": "wood_tablet",
      "name": "木制记录板",
      "phase": "solid",
      "tags": [
        "solid",
        "recordable",
        "flammable"
      ],
      "hardness": 3,
      "mass": 0.35,
      "color": [
        137,
        96,
        57
      ]
    },
    {
      "id": 28,
      "key": "container",
      "name": "木制容器",
      "phase": "solid",
      "tags": [
        "solid",
        "placeable",
        "flammable"
      ],
      "hardness": 4,
      "mass": 1.4,
      "color": [
        119,
        80,
        45
      ]
    },
    {
      "id": 29,
      "key": "raw_meat",
      "name": "生肉",
      "phase": "solid",
      "tags": [
        "edible"
      ],
      "hardness": 1,
      "mass": 0.35,
      "color": [
        151,
        56,
        52
      ],
      "consume": {
        "nutrition": 24,
        "health": -3
      }
    },
    {
      "id": 30,
      "key": "hide",
      "name": "兽皮",
      "phase": "solid",
      "tags": [
        "fiber",
        "insulating"
      ],
      "hardness": 2,
      "mass": 0.8,
      "color": [
        111,
        78,
        54
      ]
    },
    {
      "id": 31,
      "key": "bone",
      "name": "骨",
      "phase": "solid",
      "tags": [
        "solid",
        "tool-material"
      ],
      "hardness": 5,
      "mass": 0.45,
      "color": [
        205,
        197,
        169
      ]
    },
    {
      "id": 32,
      "key": "spear",
      "name": "石刃长矛",
      "phase": "solid",
      "tags": [
        "solid",
        "tool"
      ],
      "hardness": 7,
      "mass": 1.5,
      "color": [
        116,
        91,
        62
      ]
    },
    {
      "id": 33,
      "key": "leather_clothing",
      "name": "兽皮衣",
      "phase": "solid",
      "tags": [
        "insulating"
      ],
      "hardness": 3,
      "mass": 1.1,
      "color": [
        92,
        63,
        45
      ]
    },
    {
      "id": 34,
      "key": "herbal_medicine",
      "name": "草药",
      "phase": "solid",
      "tags": [
        "edible"
      ],
      "hardness": 1,
      "mass": 0.12,
      "color": [
        88,
        125,
        71
      ],
      "consume": {
        "nutrition": 2,
        "health": 12
      }
    },
    {
      "id": 35,
      "key": "charcoal",
      "name": "木炭",
      "phase": "solid",
      "tags": [
        "solid",
        "fuel"
      ],
      "hardness": 2,
      "mass": 0.35,
      "color": [
        48,
        47,
        45
      ]
    },
    {
      "id": 36,
      "key": "bone_tool",
      "name": "骨制工具",
      "phase": "solid",
      "tags": [
        "solid",
        "tool"
      ],
      "hardness": 5,
      "mass": 0.55,
      "color": [
        194,
        185,
        154
      ]
    },
    {
      "id": 37,
      "key": "clay",
      "name": "黏土",
      "phase": "solid",
      "tags": [
        "solid",
        "ground"
      ],
      "hardness": 2,
      "mass": 1.5,
      "color": [
        151,
        91,
        64
      ]
    },
    {
      "id": 38,
      "key": "copper_ore",
      "name": "铜矿石",
      "phase": "solid",
      "tags": [
        "solid",
        "ore",
        "tool-material"
      ],
      "hardness": 6,
      "mass": 2.3,
      "color": [
        92,
        125,
        105
      ]
    },
    {
      "id": 39,
      "key": "tin_ore",
      "name": "锡矿石",
      "phase": "solid",
      "tags": [
        "solid",
        "ore",
        "tool-material"
      ],
      "hardness": 6,
      "mass": 2.2,
      "color": [
        126,
        138,
        145
      ]
    },
    {
      "id": 40,
      "key": "iron_ore",
      "name": "铁矿石",
      "phase": "solid",
      "tags": [
        "solid",
        "ore",
        "tool-material"
      ],
      "hardness": 7,
      "mass": 2.7,
      "color": [
        111,
        79,
        66
      ]
    },
    {
      "id": 41,
      "key": "wood_tool",
      "name": "木制生产工具",
      "phase": "solid",
      "tags": [
        "solid",
        "tool"
      ],
      "hardness": 4,
      "mass": 0.8,
      "color": [
        133,
        88,
        48
      ]
    },
    {
      "id": 42,
      "key": "stone_hoe",
      "name": "石锄与石镰",
      "phase": "solid",
      "tags": [
        "solid",
        "tool"
      ],
      "hardness": 7,
      "mass": 1.4,
      "color": [
        113,
        111,
        103
      ]
    },
    {
      "id": 43,
      "key": "copper_charge",
      "name": "铜矿炭料",
      "phase": "solid",
      "tags": [
        "solid",
        "ore"
      ],
      "hardness": 4,
      "mass": 1.7,
      "color": [
        76,
        91,
        77
      ]
    },
    {
      "id": 44,
      "key": "tin_charge",
      "name": "锡矿炭料",
      "phase": "solid",
      "tags": [
        "solid",
        "ore"
      ],
      "hardness": 4,
      "mass": 1.6,
      "color": [
        94,
        100,
        104
      ]
    },
    {
      "id": 45,
      "key": "iron_charge",
      "name": "铁矿炭料",
      "phase": "solid",
      "tags": [
        "solid",
        "ore"
      ],
      "hardness": 5,
      "mass": 1.9,
      "color": [
        79,
        61,
        54
      ]
    },
    {
      "id": 46,
      "key": "copper",
      "name": "铜",
      "phase": "solid",
      "tags": [
        "solid",
        "metal",
        "tool-material"
      ],
      "hardness": 5,
      "mass": 2.1,
      "color": [
        181,
        101,
        55
      ]
    },
    {
      "id": 47,
      "key": "tin",
      "name": "锡",
      "phase": "solid",
      "tags": [
        "solid",
        "metal",
        "tool-material"
      ],
      "hardness": 4,
      "mass": 1.8,
      "color": [
        174,
        184,
        185
      ]
    },
    {
      "id": 48,
      "key": "bronze",
      "name": "青铜",
      "phase": "solid",
      "tags": [
        "solid",
        "metal",
        "building",
        "tool-material"
      ],
      "hardness": 8,
      "mass": 2.2,
      "color": [
        176,
        121,
        54
      ]
    },
    {
      "id": 49,
      "key": "iron_bloom",
      "name": "海绵铁",
      "phase": "solid",
      "tags": [
        "solid",
        "metal",
        "tool-material"
      ],
      "hardness": 7,
      "mass": 2.3,
      "color": [
        91,
        85,
        79
      ]
    },
    {
      "id": 50,
      "key": "iron",
      "name": "锻铁",
      "phase": "solid",
      "tags": [
        "solid",
        "metal",
        "building",
        "tool-material"
      ],
      "hardness": 9,
      "mass": 2.5,
      "color": [
        93,
        99,
        101
      ]
    },
    {
      "id": 51,
      "key": "bronze_tool",
      "name": "青铜生产工具",
      "phase": "solid",
      "tags": [
        "solid",
        "tool",
        "metal"
      ],
      "hardness": 8,
      "mass": 1.2,
      "color": [
        185,
        128,
        56
      ]
    },
    {
      "id": 52,
      "key": "iron_tool",
      "name": "铁制生产工具",
      "phase": "solid",
      "tags": [
        "solid",
        "tool",
        "metal"
      ],
      "hardness": 9,
      "mass": 1.3,
      "color": [
        102,
        108,
        110
      ]
    },
    {
      "id": 53,
      "key": "fired_brick",
      "name": "烧结砖",
      "phase": "solid",
      "tags": [
        "solid",
        "building"
      ],
      "hardness": 6,
      "mass": 1.4,
      "color": [
        159,
        78,
        52
      ]
    },
    {
      "id": 54,
      "key": "council_hearth",
      "name": "议事火塘",
      "phase": "solid",
      "tags": [
        "solid",
        "building",
        "placeable",
        "facility",
        "meeting-place",
        "insulating"
      ],
      "hardness": 5,
      "mass": 2.1,
      "color": [
        134,
        76,
        43
      ]
    },
    {
      "id": 55,
      "key": "workshop",
      "name": "工具棚",
      "phase": "solid",
      "tags": [
        "solid",
        "building",
        "placeable",
        "facility",
        "workstation"
      ],
      "hardness": 6,
      "mass": 2.2,
      "color": [
        126,
        91,
        56
      ]
    },
    {
      "id": 56,
      "key": "granary",
      "name": "公共谷仓",
      "phase": "solid",
      "tags": [
        "solid",
        "building",
        "placeable",
        "facility",
        "storage"
      ],
      "hardness": 6,
      "mass": 2.6,
      "color": [
        157,
        118,
        60
      ]
    },
    {
      "id": 57,
      "key": "cistern",
      "name": "蓄水井",
      "phase": "solid",
      "tags": [
        "solid",
        "building",
        "placeable",
        "facility",
        "water-source",
        "drinkable"
      ],
      "hardness": 7,
      "mass": 3,
      "color": [
        80,
        126,
        144
      ],
      "consume": {
        "hydration": 54
      }
    },
    {
      "id": 58,
      "key": "kiln",
      "name": "陶窑",
      "phase": "solid",
      "tags": [
        "solid",
        "building",
        "placeable",
        "facility",
        "workstation",
        "hot"
      ],
      "hardness": 7,
      "mass": 3.2,
      "color": [
        143,
        73,
        49
      ]
    },
    {
      "id": 59,
      "key": "mill",
      "name": "磨坊",
      "phase": "solid",
      "tags": [
        "solid",
        "building",
        "placeable",
        "facility",
        "workstation"
      ],
      "hardness": 7,
      "mass": 3.3,
      "color": [
        132,
        121,
        92
      ]
    },
    {
      "id": 60,
      "key": "civic_hall",
      "name": "城邦议政厅核心",
      "phase": "solid",
      "tags": [
        "solid",
        "building",
        "placeable",
        "facility",
        "meeting-place",
        "insulating"
      ],
      "hardness": 8,
      "mass": 3.5,
      "color": [
        169,
        105,
        69
      ]
    },
    {
      "id": 61,
      "key": "foundry",
      "name": "青铜铸造作坊",
      "phase": "solid",
      "tags": [
        "solid",
        "building",
        "placeable",
        "facility",
        "workstation",
        "hot"
      ],
      "hardness": 8,
      "mass": 3.8,
      "color": [
        154,
        91,
        45
      ]
    },
    {
      "id": 62,
      "key": "smithy",
      "name": "铁匠铺锻炉",
      "phase": "solid",
      "tags": [
        "solid",
        "building",
        "placeable",
        "facility",
        "workstation",
        "hot"
      ],
      "hardness": 9,
      "mass": 4,
      "color": [
        88,
        78,
        72
      ]
    },
    {
      "id": 63,
      "key": "keep_core",
      "name": "城堡议事核心",
      "phase": "solid",
      "tags": [
        "solid",
        "building",
        "placeable",
        "facility",
        "meeting-place",
        "insulating"
      ],
      "hardness": 9,
      "mass": 4.2,
      "color": [
        89,
        91,
        92
      ]
    },
    {
      "id": 64,
      "key": "water_wheel",
      "name": "水轮",
      "phase": "solid",
      "tags": [
        "solid",
        "building",
        "placeable"
      ],
      "hardness": 5,
      "mass": 2.2,
      "color": [
        126,
        87,
        48
      ]
    },
    {
      "id": 65,
      "key": "drive_shaft",
      "name": "青铜传动轴",
      "phase": "solid",
      "tags": [
        "solid",
        "building",
        "placeable",
        "metal"
      ],
      "hardness": 8,
      "mass": 1.8,
      "color": [
        161,
        111,
        50
      ]
    },
    {
      "id": 66,
      "key": "broken_drive_shaft",
      "name": "断裂的传动轴",
      "phase": "solid",
      "tags": [
        "solid",
        "placeable",
        "metal"
      ],
      "hardness": 5,
      "mass": 1.7,
      "color": [
        104,
        78,
        50
      ]
    }
  ],
  "recipes": [
    {
      "id": "shape-plank",
      "type": "combine",
      "inputs": [
        {
          "materialId": 13,
          "key": "wood",
          "name": "木材",
          "quantity": 2,
          "color": [
            91,
            61,
            38
          ],
          "tags": [
            "solid",
            "fuel",
            "building",
            "tool-material",
            "flammable"
          ]
        }
      ],
      "tools": [],
      "targets": [],
      "output": {
        "materialId": 19,
        "key": "plank",
        "name": "木板",
        "quantity": 2,
        "color": [
          155,
          111,
          65
        ],
        "tags": [
          "solid",
          "building",
          "fuel",
          "flammable"
        ]
      }
    },
    {
      "id": "twist-fiber",
      "type": "combine",
      "inputs": [
        {
          "materialId": 20,
          "key": "fiber",
          "name": "纤维",
          "quantity": 2,
          "color": [
            173,
            158,
            116
          ],
          "tags": [
            "fiber",
            "flammable"
          ]
        }
      ],
      "tools": [],
      "targets": [],
      "output": {
        "materialId": 23,
        "key": "rope",
        "name": "绳",
        "quantity": 1,
        "color": [
          167,
          139,
          91
        ],
        "tags": [
          "fiber",
          "building",
          "flammable"
        ]
      }
    },
    {
      "id": "haft-stone",
      "type": "combine",
      "inputs": [
        {
          "materialId": 1,
          "key": "stone",
          "name": "石",
          "quantity": 1,
          "color": [
            111,
            108,
            102
          ],
          "tags": [
            "solid",
            "ground",
            "building",
            "tool-material"
          ]
        },
        {
          "materialId": 13,
          "key": "wood",
          "name": "木材",
          "quantity": 1,
          "color": [
            91,
            61,
            38
          ],
          "tags": [
            "solid",
            "fuel",
            "building",
            "tool-material",
            "flammable"
          ]
        }
      ],
      "tools": [],
      "targets": [],
      "output": {
        "materialId": 24,
        "key": "stone_tool",
        "name": "石制工具",
        "quantity": 1,
        "color": [
          122,
          119,
          109
        ],
        "tags": [
          "solid",
          "tool"
        ]
      }
    },
    {
      "id": "bind-clothing",
      "type": "combine",
      "inputs": [
        {
          "materialId": 23,
          "key": "rope",
          "name": "绳",
          "quantity": 1,
          "color": [
            167,
            139,
            91
          ],
          "tags": [
            "fiber",
            "building",
            "flammable"
          ]
        },
        {
          "materialId": 20,
          "key": "fiber",
          "name": "纤维",
          "quantity": 1,
          "color": [
            173,
            158,
            116
          ],
          "tags": [
            "fiber",
            "flammable"
          ]
        }
      ],
      "tools": [],
      "targets": [],
      "output": {
        "materialId": 26,
        "key": "clothing",
        "name": "衣物",
        "quantity": 1,
        "color": [
          123,
          91,
          73
        ],
        "tags": [
          "insulating"
        ]
      }
    },
    {
      "id": "join-plank-container",
      "type": "combine",
      "inputs": [
        {
          "materialId": 19,
          "key": "plank",
          "name": "木板",
          "quantity": 2,
          "color": [
            155,
            111,
            65
          ],
          "tags": [
            "solid",
            "building",
            "fuel",
            "flammable"
          ]
        }
      ],
      "tools": [],
      "targets": [],
      "output": {
        "materialId": 28,
        "key": "container",
        "name": "木制容器",
        "quantity": 1,
        "color": [
          119,
          80,
          45
        ],
        "tags": [
          "solid",
          "placeable",
          "flammable"
        ]
      }
    },
    {
      "id": "haft-spear",
      "type": "combine",
      "inputs": [
        {
          "materialId": 24,
          "key": "stone_tool",
          "name": "石制工具",
          "quantity": 1,
          "color": [
            122,
            119,
            109
          ],
          "tags": [
            "solid",
            "tool"
          ]
        },
        {
          "materialId": 13,
          "key": "wood",
          "name": "木材",
          "quantity": 1,
          "color": [
            91,
            61,
            38
          ],
          "tags": [
            "solid",
            "fuel",
            "building",
            "tool-material",
            "flammable"
          ]
        }
      ],
      "tools": [],
      "targets": [],
      "output": {
        "materialId": 32,
        "key": "spear",
        "name": "石刃长矛",
        "quantity": 1,
        "color": [
          116,
          91,
          62
        ],
        "tags": [
          "solid",
          "tool"
        ]
      }
    },
    {
      "id": "sew-hide-clothing",
      "type": "combine",
      "inputs": [
        {
          "materialId": 30,
          "key": "hide",
          "name": "兽皮",
          "quantity": 1,
          "color": [
            111,
            78,
            54
          ],
          "tags": [
            "fiber",
            "insulating"
          ]
        },
        {
          "materialId": 23,
          "key": "rope",
          "name": "绳",
          "quantity": 1,
          "color": [
            167,
            139,
            91
          ],
          "tags": [
            "fiber",
            "building",
            "flammable"
          ]
        }
      ],
      "tools": [],
      "targets": [],
      "output": {
        "materialId": 33,
        "key": "leather_clothing",
        "name": "兽皮衣",
        "quantity": 1,
        "color": [
          92,
          63,
          45
        ],
        "tags": [
          "insulating"
        ]
      }
    },
    {
      "id": "shape-bone-tool",
      "type": "combine",
      "inputs": [
        {
          "materialId": 31,
          "key": "bone",
          "name": "骨",
          "quantity": 1,
          "color": [
            205,
            197,
            169
          ],
          "tags": [
            "solid",
            "tool-material"
          ]
        },
        {
          "materialId": 1,
          "key": "stone",
          "name": "石",
          "quantity": 1,
          "color": [
            111,
            108,
            102
          ],
          "tags": [
            "solid",
            "ground",
            "building",
            "tool-material"
          ]
        }
      ],
      "tools": [],
      "targets": [],
      "output": {
        "materialId": 36,
        "key": "bone_tool",
        "name": "骨制工具",
        "quantity": 1,
        "color": [
          194,
          185,
          154
        ],
        "tags": [
          "solid",
          "tool"
        ]
      }
    },
    {
      "id": "bind-herbal-medicine",
      "type": "combine",
      "inputs": [
        {
          "materialId": 14,
          "key": "leaves",
          "name": "树叶",
          "quantity": 1,
          "color": [
            44,
            78,
            42
          ],
          "tags": [
            "plant",
            "flammable"
          ]
        },
        {
          "materialId": 20,
          "key": "fiber",
          "name": "纤维",
          "quantity": 1,
          "color": [
            173,
            158,
            116
          ],
          "tags": [
            "fiber",
            "flammable"
          ]
        }
      ],
      "tools": [],
      "targets": [],
      "output": {
        "materialId": 34,
        "key": "herbal_medicine",
        "name": "草药",
        "quantity": 1,
        "color": [
          88,
          125,
          71
        ],
        "tags": [
          "edible"
        ]
      }
    },
    {
      "id": "shape-wood-production-tool",
      "type": "combine",
      "inputs": [
        {
          "materialId": 13,
          "key": "wood",
          "name": "木材",
          "quantity": 1,
          "color": [
            91,
            61,
            38
          ],
          "tags": [
            "solid",
            "fuel",
            "building",
            "tool-material",
            "flammable"
          ]
        },
        {
          "materialId": 23,
          "key": "rope",
          "name": "绳",
          "quantity": 1,
          "color": [
            167,
            139,
            91
          ],
          "tags": [
            "fiber",
            "building",
            "flammable"
          ]
        }
      ],
      "tools": [],
      "targets": [],
      "output": {
        "materialId": 41,
        "key": "wood_tool",
        "name": "木制生产工具",
        "quantity": 1,
        "color": [
          133,
          88,
          48
        ],
        "tags": [
          "solid",
          "tool"
        ]
      }
    },
    {
      "id": "haft-stone-field-tool",
      "type": "combine",
      "inputs": [
        {
          "materialId": 24,
          "key": "stone_tool",
          "name": "石制工具",
          "quantity": 1,
          "color": [
            122,
            119,
            109
          ],
          "tags": [
            "solid",
            "tool"
          ]
        },
        {
          "materialId": 19,
          "key": "plank",
          "name": "木板",
          "quantity": 1,
          "color": [
            155,
            111,
            65
          ],
          "tags": [
            "solid",
            "building",
            "fuel",
            "flammable"
          ]
        }
      ],
      "tools": [],
      "targets": [],
      "output": {
        "materialId": 42,
        "key": "stone_hoe",
        "name": "石锄与石镰",
        "quantity": 1,
        "color": [
          113,
          111,
          103
        ],
        "tags": [
          "solid",
          "tool"
        ]
      }
    },
    {
      "id": "assemble-council-hearth",
      "type": "combine",
      "inputs": [
        {
          "materialId": 19,
          "key": "plank",
          "name": "木板",
          "quantity": 1,
          "color": [
            155,
            111,
            65
          ],
          "tags": [
            "solid",
            "building",
            "fuel",
            "flammable"
          ]
        },
        {
          "materialId": 23,
          "key": "rope",
          "name": "绳",
          "quantity": 1,
          "color": [
            167,
            139,
            91
          ],
          "tags": [
            "fiber",
            "building",
            "flammable"
          ]
        }
      ],
      "tools": [],
      "targets": [],
      "output": {
        "materialId": 54,
        "key": "council_hearth",
        "name": "议事火塘",
        "quantity": 1,
        "color": [
          134,
          76,
          43
        ],
        "tags": [
          "solid",
          "building",
          "placeable",
          "facility",
          "meeting-place",
          "insulating"
        ]
      }
    },
    {
      "id": "assemble-workshop",
      "type": "combine",
      "inputs": [
        {
          "materialId": 19,
          "key": "plank",
          "name": "木板",
          "quantity": 1,
          "color": [
            155,
            111,
            65
          ],
          "tags": [
            "solid",
            "building",
            "fuel",
            "flammable"
          ]
        },
        {
          "materialId": 27,
          "key": "wood_tablet",
          "name": "木制记录板",
          "quantity": 1,
          "color": [
            137,
            96,
            57
          ],
          "tags": [
            "solid",
            "recordable",
            "flammable"
          ]
        }
      ],
      "tools": [],
      "targets": [],
      "output": {
        "materialId": 55,
        "key": "workshop",
        "name": "工具棚",
        "quantity": 1,
        "color": [
          126,
          91,
          56
        ],
        "tags": [
          "solid",
          "building",
          "placeable",
          "facility",
          "workstation"
        ]
      }
    },
    {
      "id": "assemble-granary",
      "type": "combine",
      "inputs": [
        {
          "materialId": 28,
          "key": "container",
          "name": "木制容器",
          "quantity": 1,
          "color": [
            119,
            80,
            45
          ],
          "tags": [
            "solid",
            "placeable",
            "flammable"
          ]
        },
        {
          "materialId": 19,
          "key": "plank",
          "name": "木板",
          "quantity": 1,
          "color": [
            155,
            111,
            65
          ],
          "tags": [
            "solid",
            "building",
            "fuel",
            "flammable"
          ]
        }
      ],
      "tools": [],
      "targets": [],
      "output": {
        "materialId": 56,
        "key": "granary",
        "name": "公共谷仓",
        "quantity": 1,
        "color": [
          157,
          118,
          60
        ],
        "tags": [
          "solid",
          "building",
          "placeable",
          "facility",
          "storage"
        ]
      }
    },
    {
      "id": "line-cistern",
      "type": "combine",
      "inputs": [
        {
          "materialId": 28,
          "key": "container",
          "name": "木制容器",
          "quantity": 1,
          "color": [
            119,
            80,
            45
          ],
          "tags": [
            "solid",
            "placeable",
            "flammable"
          ]
        },
        {
          "materialId": 1,
          "key": "stone",
          "name": "石",
          "quantity": 1,
          "color": [
            111,
            108,
            102
          ],
          "tags": [
            "solid",
            "ground",
            "building",
            "tool-material"
          ]
        }
      ],
      "tools": [],
      "targets": [],
      "output": {
        "materialId": 57,
        "key": "cistern",
        "name": "蓄水井",
        "quantity": 1,
        "color": [
          80,
          126,
          144
        ],
        "tags": [
          "solid",
          "building",
          "placeable",
          "facility",
          "water-source",
          "drinkable"
        ]
      }
    },
    {
      "id": "build-kiln",
      "type": "combine",
      "inputs": [
        {
          "materialId": 37,
          "key": "clay",
          "name": "黏土",
          "quantity": 1,
          "color": [
            151,
            91,
            64
          ],
          "tags": [
            "solid",
            "ground"
          ]
        },
        {
          "materialId": 1,
          "key": "stone",
          "name": "石",
          "quantity": 1,
          "color": [
            111,
            108,
            102
          ],
          "tags": [
            "solid",
            "ground",
            "building",
            "tool-material"
          ]
        }
      ],
      "tools": [],
      "targets": [],
      "output": {
        "materialId": 58,
        "key": "kiln",
        "name": "陶窑",
        "quantity": 1,
        "color": [
          143,
          73,
          49
        ],
        "tags": [
          "solid",
          "building",
          "placeable",
          "facility",
          "workstation",
          "hot"
        ]
      }
    },
    {
      "id": "build-mill",
      "type": "combine",
      "inputs": [
        {
          "materialId": 1,
          "key": "stone",
          "name": "石",
          "quantity": 1,
          "color": [
            111,
            108,
            102
          ],
          "tags": [
            "solid",
            "ground",
            "building",
            "tool-material"
          ]
        },
        {
          "materialId": 19,
          "key": "plank",
          "name": "木板",
          "quantity": 1,
          "color": [
            155,
            111,
            65
          ],
          "tags": [
            "solid",
            "building",
            "fuel",
            "flammable"
          ]
        }
      ],
      "tools": [],
      "targets": [],
      "output": {
        "materialId": 59,
        "key": "mill",
        "name": "磨坊",
        "quantity": 1,
        "color": [
          132,
          121,
          92
        ],
        "tags": [
          "solid",
          "building",
          "placeable",
          "facility",
          "workstation"
        ]
      }
    },
    {
      "id": "prepare-copper-charge",
      "type": "combine",
      "inputs": [
        {
          "materialId": 38,
          "key": "copper_ore",
          "name": "铜矿石",
          "quantity": 1,
          "color": [
            92,
            125,
            105
          ],
          "tags": [
            "solid",
            "ore",
            "tool-material"
          ]
        },
        {
          "materialId": 35,
          "key": "charcoal",
          "name": "木炭",
          "quantity": 1,
          "color": [
            48,
            47,
            45
          ],
          "tags": [
            "solid",
            "fuel"
          ]
        }
      ],
      "tools": [],
      "targets": [],
      "output": {
        "materialId": 43,
        "key": "copper_charge",
        "name": "铜矿炭料",
        "quantity": 1,
        "color": [
          76,
          91,
          77
        ],
        "tags": [
          "solid",
          "ore"
        ]
      }
    },
    {
      "id": "prepare-tin-charge",
      "type": "combine",
      "inputs": [
        {
          "materialId": 39,
          "key": "tin_ore",
          "name": "锡矿石",
          "quantity": 1,
          "color": [
            126,
            138,
            145
          ],
          "tags": [
            "solid",
            "ore",
            "tool-material"
          ]
        },
        {
          "materialId": 35,
          "key": "charcoal",
          "name": "木炭",
          "quantity": 1,
          "color": [
            48,
            47,
            45
          ],
          "tags": [
            "solid",
            "fuel"
          ]
        }
      ],
      "tools": [],
      "targets": [],
      "output": {
        "materialId": 44,
        "key": "tin_charge",
        "name": "锡矿炭料",
        "quantity": 1,
        "color": [
          94,
          100,
          104
        ],
        "tags": [
          "solid",
          "ore"
        ]
      }
    },
    {
      "id": "prepare-iron-charge",
      "type": "combine",
      "inputs": [
        {
          "materialId": 40,
          "key": "iron_ore",
          "name": "铁矿石",
          "quantity": 1,
          "color": [
            111,
            79,
            66
          ],
          "tags": [
            "solid",
            "ore",
            "tool-material"
          ]
        },
        {
          "materialId": 35,
          "key": "charcoal",
          "name": "木炭",
          "quantity": 1,
          "color": [
            48,
            47,
            45
          ],
          "tags": [
            "solid",
            "fuel"
          ]
        }
      ],
      "tools": [],
      "targets": [],
      "output": {
        "materialId": 45,
        "key": "iron_charge",
        "name": "铁矿炭料",
        "quantity": 1,
        "color": [
          79,
          61,
          54
        ],
        "tags": [
          "solid",
          "ore"
        ]
      }
    },
    {
      "id": "alloy-bronze",
      "type": "combine",
      "inputs": [
        {
          "materialId": 46,
          "key": "copper",
          "name": "铜",
          "quantity": 1,
          "color": [
            181,
            101,
            55
          ],
          "tags": [
            "solid",
            "metal",
            "tool-material"
          ]
        },
        {
          "materialId": 47,
          "key": "tin",
          "name": "锡",
          "quantity": 1,
          "color": [
            174,
            184,
            185
          ],
          "tags": [
            "solid",
            "metal",
            "tool-material"
          ]
        }
      ],
      "tools": [],
      "targets": [],
      "output": {
        "materialId": 48,
        "key": "bronze",
        "name": "青铜",
        "quantity": 1,
        "color": [
          176,
          121,
          54
        ],
        "tags": [
          "solid",
          "metal",
          "building",
          "tool-material"
        ]
      }
    },
    {
      "id": "cast-bronze-tool",
      "type": "combine",
      "inputs": [
        {
          "materialId": 48,
          "key": "bronze",
          "name": "青铜",
          "quantity": 1,
          "color": [
            176,
            121,
            54
          ],
          "tags": [
            "solid",
            "metal",
            "building",
            "tool-material"
          ]
        },
        {
          "materialId": 13,
          "key": "wood",
          "name": "木材",
          "quantity": 1,
          "color": [
            91,
            61,
            38
          ],
          "tags": [
            "solid",
            "fuel",
            "building",
            "tool-material",
            "flammable"
          ]
        }
      ],
      "tools": [],
      "targets": [],
      "output": {
        "materialId": 51,
        "key": "bronze_tool",
        "name": "青铜生产工具",
        "quantity": 1,
        "color": [
          185,
          128,
          56
        ],
        "tags": [
          "solid",
          "tool",
          "metal"
        ]
      }
    },
    {
      "id": "assemble-civic-hall-core",
      "type": "combine",
      "inputs": [
        {
          "materialId": 53,
          "key": "fired_brick",
          "name": "烧结砖",
          "quantity": 1,
          "color": [
            159,
            78,
            52
          ],
          "tags": [
            "solid",
            "building"
          ]
        },
        {
          "materialId": 27,
          "key": "wood_tablet",
          "name": "木制记录板",
          "quantity": 1,
          "color": [
            137,
            96,
            57
          ],
          "tags": [
            "solid",
            "recordable",
            "flammable"
          ]
        }
      ],
      "tools": [],
      "targets": [],
      "output": {
        "materialId": 60,
        "key": "civic_hall",
        "name": "城邦议政厅核心",
        "quantity": 1,
        "color": [
          169,
          105,
          69
        ],
        "tags": [
          "solid",
          "building",
          "placeable",
          "facility",
          "meeting-place",
          "insulating"
        ]
      }
    },
    {
      "id": "build-foundry",
      "type": "combine",
      "inputs": [
        {
          "materialId": 48,
          "key": "bronze",
          "name": "青铜",
          "quantity": 1,
          "color": [
            176,
            121,
            54
          ],
          "tags": [
            "solid",
            "metal",
            "building",
            "tool-material"
          ]
        },
        {
          "materialId": 1,
          "key": "stone",
          "name": "石",
          "quantity": 1,
          "color": [
            111,
            108,
            102
          ],
          "tags": [
            "solid",
            "ground",
            "building",
            "tool-material"
          ]
        }
      ],
      "tools": [],
      "targets": [],
      "output": {
        "materialId": 61,
        "key": "foundry",
        "name": "青铜铸造作坊",
        "quantity": 1,
        "color": [
          154,
          91,
          45
        ],
        "tags": [
          "solid",
          "building",
          "placeable",
          "facility",
          "workstation",
          "hot"
        ]
      }
    },
    {
      "id": "build-smithy",
      "type": "combine",
      "inputs": [
        {
          "materialId": 48,
          "key": "bronze",
          "name": "青铜",
          "quantity": 1,
          "color": [
            176,
            121,
            54
          ],
          "tags": [
            "solid",
            "metal",
            "building",
            "tool-material"
          ]
        },
        {
          "materialId": 53,
          "key": "fired_brick",
          "name": "烧结砖",
          "quantity": 1,
          "color": [
            159,
            78,
            52
          ],
          "tags": [
            "solid",
            "building"
          ]
        }
      ],
      "tools": [],
      "targets": [],
      "output": {
        "materialId": 62,
        "key": "smithy",
        "name": "铁匠铺锻炉",
        "quantity": 1,
        "color": [
          88,
          78,
          72
        ],
        "tags": [
          "solid",
          "building",
          "placeable",
          "facility",
          "workstation",
          "hot"
        ]
      }
    },
    {
      "id": "consolidate-iron-bloom",
      "type": "combine",
      "inputs": [
        {
          "materialId": 49,
          "key": "iron_bloom",
          "name": "海绵铁",
          "quantity": 1,
          "color": [
            91,
            85,
            79
          ],
          "tags": [
            "solid",
            "metal",
            "tool-material"
          ]
        },
        {
          "materialId": 35,
          "key": "charcoal",
          "name": "木炭",
          "quantity": 1,
          "color": [
            48,
            47,
            45
          ],
          "tags": [
            "solid",
            "fuel"
          ]
        }
      ],
      "tools": [],
      "targets": [],
      "output": {
        "materialId": 50,
        "key": "iron",
        "name": "锻铁",
        "quantity": 1,
        "color": [
          93,
          99,
          101
        ],
        "tags": [
          "solid",
          "metal",
          "building",
          "tool-material"
        ]
      }
    },
    {
      "id": "forge-iron-tool",
      "type": "combine",
      "inputs": [
        {
          "materialId": 50,
          "key": "iron",
          "name": "锻铁",
          "quantity": 1,
          "color": [
            93,
            99,
            101
          ],
          "tags": [
            "solid",
            "metal",
            "building",
            "tool-material"
          ]
        },
        {
          "materialId": 13,
          "key": "wood",
          "name": "木材",
          "quantity": 1,
          "color": [
            91,
            61,
            38
          ],
          "tags": [
            "solid",
            "fuel",
            "building",
            "tool-material",
            "flammable"
          ]
        }
      ],
      "tools": [],
      "targets": [],
      "output": {
        "materialId": 52,
        "key": "iron_tool",
        "name": "铁制生产工具",
        "quantity": 1,
        "color": [
          102,
          108,
          110
        ],
        "tags": [
          "solid",
          "tool",
          "metal"
        ]
      }
    },
    {
      "id": "assemble-keep-core",
      "type": "combine",
      "inputs": [
        {
          "materialId": 50,
          "key": "iron",
          "name": "锻铁",
          "quantity": 1,
          "color": [
            93,
            99,
            101
          ],
          "tags": [
            "solid",
            "metal",
            "building",
            "tool-material"
          ]
        },
        {
          "materialId": 53,
          "key": "fired_brick",
          "name": "烧结砖",
          "quantity": 1,
          "color": [
            159,
            78,
            52
          ],
          "tags": [
            "solid",
            "building"
          ]
        }
      ],
      "tools": [],
      "targets": [],
      "output": {
        "materialId": 63,
        "key": "keep_core",
        "name": "城堡议事核心",
        "quantity": 1,
        "color": [
          89,
          91,
          92
        ],
        "tags": [
          "solid",
          "building",
          "placeable",
          "facility",
          "meeting-place",
          "insulating"
        ]
      }
    },
    {
      "id": "assemble-water-wheel",
      "type": "combine",
      "inputs": [
        {
          "materialId": 19,
          "key": "plank",
          "name": "木板",
          "quantity": 1,
          "color": [
            155,
            111,
            65
          ],
          "tags": [
            "solid",
            "building",
            "fuel",
            "flammable"
          ]
        },
        {
          "materialId": 20,
          "key": "fiber",
          "name": "纤维",
          "quantity": 1,
          "color": [
            173,
            158,
            116
          ],
          "tags": [
            "fiber",
            "flammable"
          ]
        }
      ],
      "tools": [],
      "targets": [],
      "output": {
        "materialId": 64,
        "key": "water_wheel",
        "name": "水轮",
        "quantity": 1,
        "color": [
          126,
          87,
          48
        ],
        "tags": [
          "solid",
          "building",
          "placeable"
        ]
      }
    },
    {
      "id": "cast-drive-shaft",
      "type": "combine",
      "inputs": [
        {
          "materialId": 48,
          "key": "bronze",
          "name": "青铜",
          "quantity": 1,
          "color": [
            176,
            121,
            54
          ],
          "tags": [
            "solid",
            "metal",
            "building",
            "tool-material"
          ]
        },
        {
          "materialId": 19,
          "key": "plank",
          "name": "木板",
          "quantity": 1,
          "color": [
            155,
            111,
            65
          ],
          "tags": [
            "solid",
            "building",
            "fuel",
            "flammable"
          ]
        }
      ],
      "tools": [],
      "targets": [],
      "output": {
        "materialId": 65,
        "key": "drive_shaft",
        "name": "青铜传动轴",
        "quantity": 1,
        "color": [
          161,
          111,
          50
        ],
        "tags": [
          "solid",
          "building",
          "placeable",
          "metal"
        ]
      }
    },
    {
      "id": "friction-ignition",
      "type": "exert",
      "inputs": [
        {
          "materialId": 20,
          "key": "fiber",
          "name": "纤维",
          "quantity": 1,
          "color": [
            173,
            158,
            116
          ],
          "tags": [
            "fiber",
            "flammable"
          ]
        }
      ],
      "tools": [
        {
          "materialId": 24,
          "key": "stone_tool",
          "name": "石制工具",
          "quantity": 1,
          "color": [
            122,
            119,
            109
          ],
          "tags": [
            "solid",
            "tool"
          ]
        }
      ],
      "targets": [
        {
          "materialId": 0,
          "key": "air",
          "name": "空气",
          "quantity": 1,
          "color": [
            13,
            20,
            24
          ],
          "tags": [
            "air"
          ]
        }
      ],
      "output": {
        "materialId": 16,
        "key": "fire",
        "name": "火",
        "quantity": 1,
        "color": [
          224,
          94,
          42
        ],
        "tags": [
          "hot"
        ]
      },
      "outputLocation": "world",
      "outputPlacement": "support"
    },
    {
      "id": "carve-record-tablet",
      "type": "exert",
      "inputs": [
        {
          "materialId": 13,
          "key": "wood",
          "name": "木材",
          "quantity": 1,
          "color": [
            91,
            61,
            38
          ],
          "tags": [
            "solid",
            "fuel",
            "building",
            "tool-material",
            "flammable"
          ]
        }
      ],
      "tools": [
        {
          "materialId": 24,
          "key": "stone_tool",
          "name": "石制工具",
          "quantity": 1,
          "color": [
            122,
            119,
            109
          ],
          "tags": [
            "solid",
            "tool"
          ]
        }
      ],
      "targets": [
        {
          "materialId": 0,
          "key": "air",
          "name": "空气",
          "quantity": 1,
          "color": [
            13,
            20,
            24
          ],
          "tags": [
            "air"
          ]
        }
      ],
      "output": {
        "materialId": 27,
        "key": "wood_tablet",
        "name": "木制记录板",
        "quantity": 1,
        "color": [
          137,
          96,
          57
        ],
        "tags": [
          "solid",
          "recordable",
          "flammable"
        ]
      },
      "outputLocation": "inventory",
      "outputPlacement": null
    },
    {
      "id": "cook-food",
      "type": "expose",
      "inputs": [
        {
          "materialId": 21,
          "key": "food",
          "name": "食物",
          "quantity": 1,
          "color": [
            190,
            76,
            80
          ],
          "tags": [
            "edible"
          ]
        }
      ],
      "tools": [],
      "targets": [
        {
          "materialId": 16,
          "key": "fire",
          "name": "火",
          "quantity": 1,
          "color": [
            224,
            94,
            42
          ],
          "tags": [
            "hot"
          ]
        }
      ],
      "output": {
        "materialId": 25,
        "key": "cooked_food",
        "name": "熟食",
        "quantity": 1,
        "color": [
          174,
          91,
          49
        ],
        "tags": [
          "edible"
        ]
      }
    },
    {
      "id": "cook-raw-meat",
      "type": "expose",
      "inputs": [
        {
          "materialId": 29,
          "key": "raw_meat",
          "name": "生肉",
          "quantity": 1,
          "color": [
            151,
            56,
            52
          ],
          "tags": [
            "edible"
          ]
        }
      ],
      "tools": [],
      "targets": [
        {
          "materialId": 16,
          "key": "fire",
          "name": "火",
          "quantity": 1,
          "color": [
            224,
            94,
            42
          ],
          "tags": [
            "hot"
          ]
        }
      ],
      "output": {
        "materialId": 25,
        "key": "cooked_food",
        "name": "熟食",
        "quantity": 1,
        "color": [
          174,
          91,
          49
        ],
        "tags": [
          "edible"
        ]
      }
    },
    {
      "id": "char-wood",
      "type": "expose",
      "inputs": [
        {
          "materialId": 13,
          "key": "wood",
          "name": "木材",
          "quantity": 1,
          "color": [
            91,
            61,
            38
          ],
          "tags": [
            "solid",
            "fuel",
            "building",
            "tool-material",
            "flammable"
          ]
        }
      ],
      "tools": [],
      "targets": [
        {
          "materialId": 16,
          "key": "fire",
          "name": "火",
          "quantity": 1,
          "color": [
            224,
            94,
            42
          ],
          "tags": [
            "hot"
          ]
        }
      ],
      "output": {
        "materialId": 35,
        "key": "charcoal",
        "name": "木炭",
        "quantity": 1,
        "color": [
          48,
          47,
          45
        ],
        "tags": [
          "solid",
          "fuel"
        ]
      }
    },
    {
      "id": "char-wood-in-kiln",
      "type": "expose",
      "inputs": [
        {
          "materialId": 13,
          "key": "wood",
          "name": "木材",
          "quantity": 1,
          "color": [
            91,
            61,
            38
          ],
          "tags": [
            "solid",
            "fuel",
            "building",
            "tool-material",
            "flammable"
          ]
        }
      ],
      "tools": [],
      "targets": [
        {
          "materialId": 58,
          "key": "kiln",
          "name": "陶窑",
          "quantity": 1,
          "color": [
            143,
            73,
            49
          ],
          "tags": [
            "solid",
            "building",
            "placeable",
            "facility",
            "workstation",
            "hot"
          ]
        }
      ],
      "output": {
        "materialId": 35,
        "key": "charcoal",
        "name": "木炭",
        "quantity": 1,
        "color": [
          48,
          47,
          45
        ],
        "tags": [
          "solid",
          "fuel"
        ]
      }
    },
    {
      "id": "char-wood-in-foundry",
      "type": "expose",
      "inputs": [
        {
          "materialId": 13,
          "key": "wood",
          "name": "木材",
          "quantity": 1,
          "color": [
            91,
            61,
            38
          ],
          "tags": [
            "solid",
            "fuel",
            "building",
            "tool-material",
            "flammable"
          ]
        }
      ],
      "tools": [],
      "targets": [
        {
          "materialId": 61,
          "key": "foundry",
          "name": "青铜铸造作坊",
          "quantity": 1,
          "color": [
            154,
            91,
            45
          ],
          "tags": [
            "solid",
            "building",
            "placeable",
            "facility",
            "workstation",
            "hot"
          ]
        }
      ],
      "output": {
        "materialId": 35,
        "key": "charcoal",
        "name": "木炭",
        "quantity": 1,
        "color": [
          48,
          47,
          45
        ],
        "tags": [
          "solid",
          "fuel"
        ]
      }
    },
    {
      "id": "fire-clay-brick",
      "type": "expose",
      "inputs": [
        {
          "materialId": 37,
          "key": "clay",
          "name": "黏土",
          "quantity": 1,
          "color": [
            151,
            91,
            64
          ],
          "tags": [
            "solid",
            "ground"
          ]
        }
      ],
      "tools": [],
      "targets": [
        {
          "materialId": 16,
          "key": "fire",
          "name": "火",
          "quantity": 1,
          "color": [
            224,
            94,
            42
          ],
          "tags": [
            "hot"
          ]
        }
      ],
      "output": {
        "materialId": 53,
        "key": "fired_brick",
        "name": "烧结砖",
        "quantity": 1,
        "color": [
          159,
          78,
          52
        ],
        "tags": [
          "solid",
          "building"
        ]
      }
    },
    {
      "id": "smelt-copper-charge",
      "type": "expose",
      "inputs": [
        {
          "materialId": 43,
          "key": "copper_charge",
          "name": "铜矿炭料",
          "quantity": 1,
          "color": [
            76,
            91,
            77
          ],
          "tags": [
            "solid",
            "ore"
          ]
        }
      ],
      "tools": [],
      "targets": [
        {
          "materialId": 58,
          "key": "kiln",
          "name": "陶窑",
          "quantity": 1,
          "color": [
            143,
            73,
            49
          ],
          "tags": [
            "solid",
            "building",
            "placeable",
            "facility",
            "workstation",
            "hot"
          ]
        }
      ],
      "output": {
        "materialId": 46,
        "key": "copper",
        "name": "铜",
        "quantity": 1,
        "color": [
          181,
          101,
          55
        ],
        "tags": [
          "solid",
          "metal",
          "tool-material"
        ]
      }
    },
    {
      "id": "smelt-tin-charge",
      "type": "expose",
      "inputs": [
        {
          "materialId": 44,
          "key": "tin_charge",
          "name": "锡矿炭料",
          "quantity": 1,
          "color": [
            94,
            100,
            104
          ],
          "tags": [
            "solid",
            "ore"
          ]
        }
      ],
      "tools": [],
      "targets": [
        {
          "materialId": 58,
          "key": "kiln",
          "name": "陶窑",
          "quantity": 1,
          "color": [
            143,
            73,
            49
          ],
          "tags": [
            "solid",
            "building",
            "placeable",
            "facility",
            "workstation",
            "hot"
          ]
        }
      ],
      "output": {
        "materialId": 47,
        "key": "tin",
        "name": "锡",
        "quantity": 1,
        "color": [
          174,
          184,
          185
        ],
        "tags": [
          "solid",
          "metal",
          "tool-material"
        ]
      }
    },
    {
      "id": "fire-clay-brick-in-kiln",
      "type": "expose",
      "inputs": [
        {
          "materialId": 37,
          "key": "clay",
          "name": "黏土",
          "quantity": 1,
          "color": [
            151,
            91,
            64
          ],
          "tags": [
            "solid",
            "ground"
          ]
        }
      ],
      "tools": [],
      "targets": [
        {
          "materialId": 58,
          "key": "kiln",
          "name": "陶窑",
          "quantity": 1,
          "color": [
            143,
            73,
            49
          ],
          "tags": [
            "solid",
            "building",
            "placeable",
            "facility",
            "workstation",
            "hot"
          ]
        }
      ],
      "output": {
        "materialId": 53,
        "key": "fired_brick",
        "name": "烧结砖",
        "quantity": 1,
        "color": [
          159,
          78,
          52
        ],
        "tags": [
          "solid",
          "building"
        ]
      }
    },
    {
      "id": "smelt-copper-charge-in-foundry",
      "type": "expose",
      "inputs": [
        {
          "materialId": 43,
          "key": "copper_charge",
          "name": "铜矿炭料",
          "quantity": 1,
          "color": [
            76,
            91,
            77
          ],
          "tags": [
            "solid",
            "ore"
          ]
        }
      ],
      "tools": [],
      "targets": [
        {
          "materialId": 61,
          "key": "foundry",
          "name": "青铜铸造作坊",
          "quantity": 1,
          "color": [
            154,
            91,
            45
          ],
          "tags": [
            "solid",
            "building",
            "placeable",
            "facility",
            "workstation",
            "hot"
          ]
        }
      ],
      "output": {
        "materialId": 46,
        "key": "copper",
        "name": "铜",
        "quantity": 1,
        "color": [
          181,
          101,
          55
        ],
        "tags": [
          "solid",
          "metal",
          "tool-material"
        ]
      }
    },
    {
      "id": "smelt-tin-charge-in-foundry",
      "type": "expose",
      "inputs": [
        {
          "materialId": 44,
          "key": "tin_charge",
          "name": "锡矿炭料",
          "quantity": 1,
          "color": [
            94,
            100,
            104
          ],
          "tags": [
            "solid",
            "ore"
          ]
        }
      ],
      "tools": [],
      "targets": [
        {
          "materialId": 61,
          "key": "foundry",
          "name": "青铜铸造作坊",
          "quantity": 1,
          "color": [
            154,
            91,
            45
          ],
          "tags": [
            "solid",
            "building",
            "placeable",
            "facility",
            "workstation",
            "hot"
          ]
        }
      ],
      "output": {
        "materialId": 47,
        "key": "tin",
        "name": "锡",
        "quantity": 1,
        "color": [
          174,
          184,
          185
        ],
        "tags": [
          "solid",
          "metal",
          "tool-material"
        ]
      }
    },
    {
      "id": "smelt-iron-charge",
      "type": "expose",
      "inputs": [
        {
          "materialId": 45,
          "key": "iron_charge",
          "name": "铁矿炭料",
          "quantity": 1,
          "color": [
            79,
            61,
            54
          ],
          "tags": [
            "solid",
            "ore"
          ]
        }
      ],
      "tools": [],
      "targets": [
        {
          "materialId": 62,
          "key": "smithy",
          "name": "铁匠铺锻炉",
          "quantity": 1,
          "color": [
            88,
            78,
            72
          ],
          "tags": [
            "solid",
            "building",
            "placeable",
            "facility",
            "workstation",
            "hot"
          ]
        }
      ],
      "output": {
        "materialId": 49,
        "key": "iron_bloom",
        "name": "海绵铁",
        "quantity": 1,
        "color": [
          91,
          85,
          79
        ],
        "tags": [
          "solid",
          "metal",
          "tool-material"
        ]
      }
    },
    {
      "id": "split-stone-with-stone-tool",
      "type": "separate",
      "inputs": [
        {
          "materialId": 1,
          "key": "stone",
          "name": "石",
          "quantity": 1,
          "color": [
            111,
            108,
            102
          ],
          "tags": [
            "solid",
            "ground",
            "building",
            "tool-material"
          ]
        }
      ],
      "tools": [
        {
          "materialId": 24,
          "key": "stone_tool",
          "name": "石制工具",
          "quantity": 1,
          "color": [
            122,
            119,
            109
          ],
          "tags": [
            "solid",
            "tool"
          ]
        }
      ],
      "targets": [],
      "output": {
        "materialId": 1,
        "key": "stone",
        "name": "石",
        "quantity": 1,
        "color": [
          111,
          108,
          102
        ],
        "tags": [
          "solid",
          "ground",
          "building",
          "tool-material"
        ]
      },
      "outputs": [
        {
          "materialId": 1,
          "key": "stone",
          "name": "石",
          "quantity": 1,
          "color": [
            111,
            108,
            102
          ],
          "tags": [
            "solid",
            "ground",
            "building",
            "tool-material"
          ]
        }
      ],
      "replacement": {
        "materialId": 0,
        "key": "air",
        "name": "空气",
        "quantity": 1,
        "color": [
          13,
          20,
          24
        ],
        "tags": [
          "air"
        ]
      }
    },
    {
      "id": "recover-plank",
      "type": "separate",
      "inputs": [
        {
          "materialId": 19,
          "key": "plank",
          "name": "木板",
          "quantity": 1,
          "color": [
            155,
            111,
            65
          ],
          "tags": [
            "solid",
            "building",
            "fuel",
            "flammable"
          ]
        }
      ],
      "tools": [],
      "targets": [],
      "output": {
        "materialId": 19,
        "key": "plank",
        "name": "木板",
        "quantity": 1,
        "color": [
          155,
          111,
          65
        ],
        "tags": [
          "solid",
          "building",
          "fuel",
          "flammable"
        ]
      },
      "outputs": [
        {
          "materialId": 19,
          "key": "plank",
          "name": "木板",
          "quantity": 1,
          "color": [
            155,
            111,
            65
          ],
          "tags": [
            "solid",
            "building",
            "fuel",
            "flammable"
          ]
        }
      ],
      "replacement": {
        "materialId": 0,
        "key": "air",
        "name": "空气",
        "quantity": 1,
        "color": [
          13,
          20,
          24
        ],
        "tags": [
          "air"
        ]
      }
    },
    {
      "id": "recover-container",
      "type": "separate",
      "inputs": [
        {
          "materialId": 28,
          "key": "container",
          "name": "木制容器",
          "quantity": 1,
          "color": [
            119,
            80,
            45
          ],
          "tags": [
            "solid",
            "placeable",
            "flammable"
          ]
        }
      ],
      "tools": [],
      "targets": [],
      "output": {
        "materialId": 28,
        "key": "container",
        "name": "木制容器",
        "quantity": 1,
        "color": [
          119,
          80,
          45
        ],
        "tags": [
          "solid",
          "placeable",
          "flammable"
        ]
      },
      "outputs": [
        {
          "materialId": 28,
          "key": "container",
          "name": "木制容器",
          "quantity": 1,
          "color": [
            119,
            80,
            45
          ],
          "tags": [
            "solid",
            "placeable",
            "flammable"
          ]
        }
      ],
      "replacement": {
        "materialId": 0,
        "key": "air",
        "name": "空气",
        "quantity": 1,
        "color": [
          13,
          20,
          24
        ],
        "tags": [
          "air"
        ]
      }
    }
  ],
  "counts": {
    "materials": 67,
    "recipes": 47,
    "combine": 30,
    "exert": 2,
    "expose": 12,
    "separate": 3
  }
};
