import { readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const labDir = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const repoDir = resolve(labDir, '..');
const catalogPath = 'three-body/src/game/voxel-assets/catalog.json';
const outputPath = resolve(labDir, 'voxel-assets-data.js');
const catalog = JSON.parse(await readFile(resolve(repoDir, catalogPath), 'utf8'));

const banner = '// Generated by npm run sync:assets. Edit the voxel asset catalog, not this file.\n';
const generated = `${banner}export const VOXEL_ASSET_CATALOG = ${JSON.stringify(catalog, null, 2)};\n`;

if (process.argv.includes('--check')) {
  const current = await readFile(outputPath, 'utf8').catch(() => '');
  if (current !== generated) throw new Error('voxel-assets-data.js is stale; run npm run sync:assets');
  console.log(`Verified ${Object.keys(catalog.assets).length} synced voxel assets`);
} else {
  await writeFile(outputPath, generated, 'utf8');
  console.log(`Synced ${Object.keys(catalog.assets).length} voxel assets into voxel-assets-data.js`);
}
