import { readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const labDir = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const repoDir = resolve(labDir, '..');

const sources = [
  {
    id: 'module-boundary',
    path: 'three-body/src/game/eland/README.md',
    eyebrow: 'CURRENT IMPLEMENTATION',
    title: 'ELAND 模块边界',
    summary: '从世界基元、领域模型到应用编排与投影层，说明当前代码如何分层，以及事实权威位于哪里。',
  },
  {
    id: 'rule-first-agent',
    path: 'docs/rule-first-agent-architecture-v1.md',
    eyebrow: 'AUTHORITATIVE DESIGN',
    title: '规则优先人物架构',
    summary: '人物决策频率、规划刻度、模型边界、失败修复与本地规则权威。',
  },
  {
    id: 'unified-agent-memory',
    path: 'docs/unified-agent-memory-v1.md',
    eyebrow: 'AGENT MEMORY',
    title: '统一人物记忆 v1',
    summary: '六类主观记忆的统一召回、真实对话、压缩、模糊、遗忘与多轮对话协调。',
  },
  {
    id: 'agent-prompt-contract',
    path: 'docs/agent-prompt-contract-v2.md',
    eyebrow: 'MODEL CONTRACT',
    title: '人物 Prompt Contract v2',
    summary: '决策、最终台词和玩家对话的权威分工、Character Card、Scene Contract 与人工真实感审阅。',
  },
  {
    id: 'person-traits',
    path: 'docs/person-traits-v1.md',
    eyebrow: 'PERSON RULES',
    title: '人物特质',
    summary: '十三种永久特质、固定先民配置、确定性遗传、随机异变和生殖、代谢、配方、母脉等领域效果。',
  },
  {
    id: 'monthly-time',
    path: 'docs/monthly-time-model-v1.md',
    eyebrow: 'RUNTIME CONTRACT',
    title: '月度时间模型',
    summary: '固定月份、15 个规划刻度、月初与月末过程、事实提交和模型事实后投影的执行契约。',
  },
  {
    id: 'spatial-action',
    path: 'docs/spatial-action-contract-v1.md',
    eyebrow: 'ACTION CONTRACT',
    title: '空间行动契约',
    summary: '人物如何从局部候选形成意图，并经移动、转移、操作、观察和沟通留下可回放事实。',
  },
  {
    id: 'pixel-world',
    path: 'docs/pixel-world-v1.md',
    eyebrow: 'WORLD STATE',
    title: '体素世界、历史与迁移',
    summary: '84 × 52 × 12 权威体素世界、确定性生成、空间投影、时间线回放与状态迁移。',
  },
  {
    id: 'evolution-loop',
    path: 'docs/evolution-iteration-loop-v1.md',
    eyebrow: 'EXPERIMENT PROTOCOL',
    title: '文明演化双闭环',
    summary: '游戏内部如何涌现，以及开发时怎样用配对、多种子实验判断规则变化是否成立。',
  },
  {
    id: 'era-ecology',
    path: 'docs/three-body-era-ecology-v1.md',
    eyebrow: 'WORLD RULES',
    title: '纪元、预言与生态',
    summary: '恒乱纪元、月度天气、智者预言、脱水休眠和生态后果的当前规则。',
  },
  {
    id: 'civilization-index',
    path: 'docs/civilization-index-v1.md',
    eyebrow: 'READ-ONLY OBSERVER',
    title: '文明指数与时代观察',
    summary: '文明指数如何从历史证据投影，以及为什么它不能进入人物目标或奖励。',
  },
  {
    id: 'capability-chains',
    path: 'docs/capability-milestone-causal-chains-v2.md',
    eyebrow: 'OBSERVER CATALOG',
    title: '能力里程碑因果链 v2',
    summary: '当前能力地图坐标的严格、守卫和复合证据口径，以及尚未被实现支持的观察边界。',
  },
  {
    id: 'capability-observer',
    path: 'docs/capability-milestones-causal-observer-v2.md',
    eyebrow: 'REPLAYABLE OBSERVER',
    title: '能力里程碑观察器 v2',
    summary: '里程碑目录、阶段门槛、重投影协议与防止观察器误报的回放守卫。',
  },
  {
    id: 'sqlite-persistence',
    path: 'docs/sqlite-persistence-v1.md',
    eyebrow: 'PERSISTENCE CONTRACT',
    title: 'SQLite 持久化',
    summary: '唯一事实库、内容块与 codec、事务边界、备份恢复和存储切换审计。',
  },
  {
    id: 'player-save',
    path: 'docs/player-save-v1.md',
    eyebrow: 'PRODUCT CONTRACT',
    title: '玩家存档与分支恢复',
    summary: '手动存档、实时恢复、分支回放、权威月份和客户端首屏裁剪的产品语义。',
  },
  {
    id: 'agent-cli',
    path: 'docs/agent-cli-v1.md',
    eyebrow: 'AGENT INTERFACE',
    title: 'Agent CLI',
    summary: '通过 HTTP 适配器诊断运行、检查领域事实、管理实时会话并执行配对实验的边界。',
  },
];

const documents = await Promise.all(sources.map(async (source) => ({
  ...source,
  content: await readFile(resolve(repoDir, source.path), 'utf8'),
})));

const banner = '// Generated by npm run sync:docs. Edit the source Markdown files, not this file.\n';
await writeFile(
  resolve(labDir, 'knowledge-docs.js'),
  `${banner}export const KNOWLEDGE_DOCUMENTS = ${JSON.stringify(documents, null, 2)};\n`,
  'utf8',
);

console.log(`Synced ${documents.length} core documents into knowledge-docs.js`);
