import { readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const labDir = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const repoDir = resolve(labDir, '..');

const sources = [
  {
    id: 'module-boundary',
    path: 'three-body/src/game/eland/README.md',
    eyebrow: 'CURRENT IMPLEMENTATION',
    title: 'ELAND 模块边界',
    summary: '从世界基元、领域模型到应用编排与投影层，说明当前代码如何分层，以及事实权威位于哪里。',
  },
  {
    id: 'rule-first-agent',
    path: 'docs/rule-first-agent-architecture-v1.md',
    eyebrow: 'AUTHORITATIVE DESIGN',
    title: '规则优先人物架构',
    summary: '人物决策频率、规划刻度、模型边界、失败修复与本地规则权威。',
  },
  {
    id: 'evolution-loop',
    path: 'docs/evolution-iteration-loop-v1.md',
    eyebrow: 'EXPERIMENT PROTOCOL',
    title: '文明演化双闭环',
    summary: '游戏内部如何涌现，以及开发时怎样用配对、多种子实验判断规则变化是否成立。',
  },
  {
    id: 'era-ecology',
    path: 'docs/three-body-era-ecology-v1.md',
    eyebrow: 'WORLD RULES',
    title: '纪元、预言与生态',
    summary: '恒乱纪元、月度天气、智者预言、脱水休眠和生态后果的当前规则。',
  },
  {
    id: 'civilization-index',
    path: 'docs/civilization-index-v1.md',
    eyebrow: 'READ-ONLY OBSERVER',
    title: '文明指数与时代观察',
    summary: '文明指数如何从历史证据投影，以及为什么它不能进入人物目标或奖励。',
  },
];

const documents = await Promise.all(sources.map(async (source) => ({
  ...source,
  content: await readFile(resolve(repoDir, source.path), 'utf8'),
})));

const banner = '// Generated by npm run sync:docs. Edit the source Markdown files, not this file.\n';
await writeFile(
  resolve(labDir, 'knowledge-docs.js'),
  `${banner}export const KNOWLEDGE_DOCUMENTS = ${JSON.stringify(documents, null, 2)};\n`,
  'utf8',
);

console.log(`Synced ${documents.length} core documents into knowledge-docs.js`);
